### ISSUE TITLE
Failed to dynamically deploy this plugin

### ISSUE THREAD

**Issue by ksanand** [devnull-tools/jenkins-notifier#6]
After building the hpi, when I tried to upload the plugin to Jenkins (1.612) and the following error was encountered. 

java.io.IOException: Failed to dynamically deploy this plugin
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1328)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1126)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:110)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Failed to install build-notification plugin
	at hudson.PluginManager.dynamicLoad(PluginManager.java:474)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1324)
	... 5 more
Caused by: jenkins.ExtensionRefreshException: hudson.plugins.persona.random.RandomPersonaFinder@867523e doesn't support refresh
	at jenkins.model.Jenkins.refreshExtensions(Jenkins.java:2224)
	at hudson.PluginManager.dynamicLoad(PluginManager.java:467)
	... 6 more

**Comment by ataxexe** [comment]
Well, this is not something related to this plugin. It's clear in the stacktrack that the problem is the Persona Plugin that doesn't support a refresh and you're trying to install a plugin without a restart in Jenkins.

I believe you're facing this problem here:

https://issues.jenkins-ci.org/browse/JENKINS-12803

**Comment by ksanand** [comment]
Sorry. I just figured that out! I restarted Jenkins and I can see the plugin installed already. Apologies. Thanks.

**Comment by ataxexe** [comment]
No problem. And thanks for using this plugin!
